### ISSUE TITLE
Use logger

### ISSUE THREAD

**Issue by gilrrei** [amgebauer/lnmmeshio#14]
Currently to stream information to the terminal, e.g. the progress bar, are done using the `print` function. This makes them difficult to turn off without modifying the source. Instead of adding a verbose flag, using python logging or in particular [loguru](https://loguru.readthedocs.io/en/stable/) gives the user the possibility to silence the logger as well as to integrate it their own scripts quite easily.

**Comment by amgebauer** [comment]
Closed via #15
